project:
  type: website
  output-dir: docs
  resources:
    - assets/files/CV.pdf
    - .nojekyll

website:
  title: "Chia-Le Yen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
